version: '3.8'

services:
  mysql:
    image: docker.io/mysql:8.0-oracle
    expose:
      - 3306
    secrets:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
    volumes:
      - ./configuration/authentication.sql:/docker-entrypoint-initdb.d/authentication.sql:ro
      - mysql_data:/var/lib/mysql	
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/MYSQL_ROOT_PASSWORD
      - MYSQL_USER_FILE=/run/secrets/MYSQL_USER
      - MYSQL_PASSWORD_FILE=/run/secrets/MYSQL_PASSWORD
      - MYSQL_DATABASE=sima_authentication
    networks:
      - internal
  
  administration-server:
    image: docker.io/simawct/administration-server:baa3b5ae
    expose:
     - 8080
    secrets:
     - MYSQL_USER
     - MYSQL_PASSWORD
    environment: 
     - "SPRING_CONFIG_IMPORT=configserver:"
     - "SPRING_PROFILES_ACTIVE=jpa"
    networks:
     - internal
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=internal"
      - 'traefik.http.routers.admin.tls=true'
      - "traefik.http.routers.admin.entrypoints=websecure"
      - "traefik.http.routers.admin.tls.certresolver=letsencrypt"
      - "traefik.http.routers.admin.rule=Host(`administration.sima.udb.edu.sv`)"
      - "traefik.http.services.admin.loadbalancer.server.port=8080"

  configuration-server:
    image: docker.io/simawct/configuration-server:b2cc6178
    expose:
     - 8080
    depends_on:
      - administration-server
    secrets:
      - GITLAB_ACCESS_USER
      - GITLAB_ACCESS_TOKEN
    configs:
      - source: cloud-configuration
        target: /app/resources/application.yml
        uid: "0"
        mode: 292
    networks:
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=internal"
      - 'traefik.http.routers.config.tls=true'
      - "traefik.http.routers.config.entrypoints=websecure"
      - "traefik.http.routers.config.tls.certresolver=letsencrypt"
      - "traefik.http.routers.config.rule=Host(`config-server.sima.udb.edu.sv`)"
      - "traefik.http.services.config.loadbalancer.server.port=8080"
  
  api-gateway:
    image: docker.io/simawct/api-gateway:4956375f
    expose:
      - 8080
    depends_on:
      - configuration-server
      - administration-server
    environment: 
      - "SPRING_CONFIG_IMPORT=configserver:"
    networks:
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=internal"
      - 'traefik.http.routers.api.tls=true'
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls.certresolver=letsencrypt"
      - "traefik.http.routers.api.rule=Host(`api.sima.udb.edu.sv`)"
      - "traefik.http.services.api.loadbalancer.server.port=8080"

  authentication-server:
    image: docker.io/simawct/authentication-server:b6d26db3
    expose: 
      - 8080
    depends_on:
      - configuration-server 
      - administration-server
    secrets:
      - MAIL_USERNAME
      - MAIL_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
      - CLIENT_ID
      - CLIENT_SECRET
      - PUBLIC_KEY
      - PRIVATE_KEY
      - JWKS_PASSWORD
    environment: 
    - "SPRING_CONFIG_IMPORT=configserver:"
    - "SPRING_PROFILES_ACTIVE=jpa"
    networks:
      - internal

  ngsi-api-server:
    image: docker.io/simawct/ngsi-api-service:a94fc0ef
    expose:
      - 8080
    depends_on:
      - configuration-server 
      - administration-server
    secrets:
      - CLIENT_ID
      - CLIENT_SECRET_CRYPT
      - MONGO_DB_USERNAME
      - MONGO_DB_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWOR
    environment: 
      - "SPRING_CONFIG_IMPORT=configserver:"
      - "SPRING_PROFILES_ACTIVE=secure,jpa"
    networks:
      - internal

  frontend:
    image: docker.io/simawct/frontend-17.3.6:0911a3b4
    expose:
      - 80
    networks:
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=internal"
      - 'traefik.http.routers.www.tls=true'
      - "traefik.http.routers.www.entrypoints=websecure"
      - "traefik.http.routers.www.tls.certresolver=letsencrypt"
      - "traefik.http.routers.www.rule=Host(`sima.udb.edu.sv`)"
      - "traefik.http.services.www.loadbalancer.server.port=80"
  
  phpmyadmin:
    image: docker.io/phpmyadmin:5.2.1-apache
    expose:
      - 80
    depends_on:
      - mysql
    secrets:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
    environment:
     - PMA_HOST=mysql
     - MYSQL_USER_FILE=/run/secrets/MYSQL_USER
     - MYSQL_PASSWORD_FILE=/run/secrets/MYSQL_PASSWORD
    networks:
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=internal"
      - 'traefik.http.routers.phpmyadmin.tls=true'
      - "traefik.http.routers.phpmyadmin.entrypoints=websecure"
      - "traefik.http.routers.phpmyadmin.tls.certresolver=letsencrypt"
      - "traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.sima.udb.edu.sv`)"
      - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80"

configs:
  cloud-configuration:
    file: ./configuration/configuration-server.yml

volumes:
  mysql_data:
   external: true
   
networks:
  internal:
   external: true

secrets:
  MONGO_DB_USERNAME:
   external: true
  MONGO_DB_PASSWORD:
   external: true
  MYSQL_ROOT_PASSWORD:
   external: true
  MAIL_USERNAME:
   external: true
  MAIL_PASSWORD:
   external: true
  MYSQL_USER:
   external: true
  MYSQL_PASSWORD:
   external: true
  GITLAB_ACCESS_USER:
   external: true
  GITLAB_ACCESS_TOKEN:
   external: true
  PRIVATE_KEY:
   external: true
  PUBLIC_KEY:
   external: true
  CLIENT_ID:
   external: true
  CLIENT_SECRET:
   external: true
  CLIENT_SECRET_CRYPT:
   external: true
  JWKS_PASSWORD:
   external: true